question_data = [
  {"text": "A slug's blood is green.", "answer": "true"},
  {"text": "Approximately one quarter of human bones are in the feet.", "answer": "true"},
  {"text": "The total surface area of human lungs is the size of a football pitch.", "answer": "true"},
  {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "true"},
  {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "false"},
  {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "true"},
  {"text": "You can lead a cow downstairs but not upstairs.", "answer": "false"},
  {"text": "Google was originally called 'Backrub'.", "answer": "true"},
  {"text": "The shortest war in history lasted for 38 minutes.", "answer": "true"},
  {"text": "Goldfish have a three-second memory span.", "answer": "false"},
  {"text": "The Eiffel Tower can be 15 cm taller during the summer.", "answer": "true"},
  {"text": "There are more stars in the universe than grains of sand on all the world's beaches.", "answer": "true"},
  {"text": "Octopuses have three hearts.", "answer": "true"},
  {"text": "The Mona Lisa has no eyebrows.", "answer": "true"},
  {"text": "Honey never spoils.", "answer": "true"},
  {"text": "Humans and dinosaurs coexisted.", "answer": "false"},
  {"text": "The unicorn is the national animal of Scotland.", "answer": "true"},
  {"text": "A sneeze travels about 100 miles per hour.", "answer": "true"},
  {"text": "Lightning never strikes the same place twice.", "answer": "false"},
  {"text": "The inventor of the Pringles can is now buried in one.", "answer": "true"},
  {"text": "Humans cannot breathe and swallow at the same time.", "answer": "true"},
  {"text": "A shrimp's heart is in its head.", "answer": "true"},
  {"text": "The human nose can detect over 1 trillion different scents.", "answer": "true"},
  {"text": "Walt Disney was the original voice of Mickey Mouse.", "answer": "true"},
  {"text": "The longest recorded flight of a chicken is thirteen seconds.", "answer": "true"},
  {"text": "The national flag of Switzerland is square.", "answer": "true"},
  {"text": "A crocodile cannot stick its tongue out.", "answer": "true"},
  {"text": "The Great Wall of China is the longest wall in the world.", "answer": "true"},
  {"text": "Venus is the hottest planet in the solar system.", "answer": "true"},
  {"text": "Humans have more than five senses.", "answer": "true"},
  {"text": "Coca-Cola was originally green.", "answer": "false"},
  {"text": "A group of flamingos is called a 'flamboyance'.", "answer": "true"},
  {"text": "The light bulb was invented by Humphry Davy.", "answer": "true"},
  {"text": "Bananas are berries, but strawberries are not.", "answer": "true"},
  {"text": "The smallest bone in the human body is found in the ear.", "answer": "true"},
  {"text": "The Atlantic Ocean is the second largest ocean on Earth.", "answer": "true"},
  {"text": "Adult humans have 206 bones in their bodies.", "answer": "true"},
  {"text": "Mauna Kea is the tallest mountain in the world when measured from base to summit.", "answer": "true"},
  {"text": "Some cats are allergic to humans.", "answer": "true"},
  {"text": "An ostrich's eye is bigger than its brain.", "answer": "true"},
  {"text": f"Humans share approximately 50% of their DNA with bananas.", "answer": "true"},
  {"text": "Sharks have been around longer than trees.", "answer": "true"},
  {"text": "An octopus's blood is blue.", "answer": "true"},
  {"text": "Cleopatra lived closer in time to the Moon landing than to the construction of the Great Pyramid of Giza.", "answer": "true"},
  {"text": "The inventor of the microwave appliance only received $2 for his discovery.", "answer": "true"},
  {"text": "Honeybees can recognize human faces.", "answer": "true"},
  {"text": "The longest recorded flight of a paper airplane is over 200 feet.", "answer": "true"},
  {"text": "A day on Venus is longer than a year on Venus.", "answer": "true"},
  {"text": "A snail can sleep for three years.", "answer": "true"},
  {"text": "An ostrich can fly at speeds of up to 60 mph.", "answer": "false"},
  {"text": "Venus is the only planet in the solar system that rotates clockwise.", "answer": "false"},
  {"text": "The Mona Lisa was painted by Vincent van Gogh.", "answer": "false"},
  {"text": "The Amazon River is the longest river in the world.", "answer": "false"}
]
